language: php

php:
    - 7.1
sudo: required
services:
    - docker
cache:
    directories:
        - vendor
        - $HOME/.composer/cache
before_script:
    - docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" stilliard/pure-ftpd:hardened
    - php tests/wait_for_ftp_service.php
    - docker exec -it ftpd_server sh -c "(echo bar; echo bar) | pure-pw useradd foo -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/foo"
install:
    - composer install
script:
    - vendor/bin/phpstan analyze -l 4 src
    - vendor/bin/phpunit
